"""empty message

Revision ID: 16d553fb55a9
Revises: 81c164ffd88b
Create Date: 2019-07-17 15:17:10.518371

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '16d553fb55a9'
down_revision = '81c164ffd88b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('t_user',
    sa.Column('user_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('password_hash', sa.String(length=120), nullable=False),
    sa.Column('username', sa.String(length=120), nullable=False),
    sa.Column('created_time', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('user_id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('password_hash'),
    sa.UniqueConstraint('username')
    )
    op.create_table('t_post',
    sa.Column('post_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('post_text', sa.String(), nullable=False),
    sa.Column('created_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('modified_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['t_user.user_id'], ),
    sa.PrimaryKeyConstraint('post_id')
    )
    op.create_table('t_comment',
    sa.Column('comment_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('post_id', sa.Integer(), nullable=True),
    sa.Column('parent_id', sa.Integer(), nullable=True),
    sa.Column('comment_text', sa.String(), nullable=False),
    sa.Column('created_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['post_id'], ['t_post.post_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['t_user.user_id'], ),
    sa.PrimaryKeyConstraint('comment_id')
    )
    op.drop_table('comment_model')
    op.drop_table('user_model')
    op.drop_table('post_model')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('post_model',
    sa.Column('post_id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('post_text', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('created_time', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('modified_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('post_id', name='post_model_pkey')
    )
    op.create_table('user_model',
    sa.Column('user_id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('email', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('password_hash', sa.VARCHAR(length=120), autoincrement=False, nullable=False),
    sa.Column('username', sa.VARCHAR(length=120), autoincrement=False, nullable=True),
    sa.Column('created_time', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('modified_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('user_id', name='user_model_pkey'),
    sa.UniqueConstraint('email', name='user_model_email_key'),
    sa.UniqueConstraint('password_hash', name='user_model_password_hash_key'),
    sa.UniqueConstraint('username', name='user_model_username_key')
    )
    op.create_table('comment_model',
    sa.Column('comment_id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('comment_text', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('created_time', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('modified_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('comment_id', name='comment_model_pkey')
    )
    op.drop_table('t_comment')
    op.drop_table('t_post')
    op.drop_table('t_user')
    # ### end Alembic commands ###
