"""empty message

Revision ID: 1d1091c5eb84
Revises: 872e92f4501c
Create Date: 2019-07-23 15:18:07.265287

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '1d1091c5eb84'
down_revision = '872e92f4501c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_model',
    sa.Column('user_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('username', sa.String(length=120), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('password_hash', sa.String(length=120), nullable=False),
    sa.Column('created_time', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('user_id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('password_hash'),
    sa.UniqueConstraint('username')
    )
    op.drop_table('t_post')
    op.drop_table('t_user')
    op.drop_table('t_comment')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('t_comment',
    sa.Column('comment_id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('post_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('parent_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('comment_text', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('created_time', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['post_id'], ['t_post.post_id'], name='t_comment_post_id_fkey'),
    sa.ForeignKeyConstraint(['user_id'], ['t_user.user_id'], name='t_comment_user_id_fkey'),
    sa.PrimaryKeyConstraint('comment_id', name='t_comment_pkey')
    )
    op.create_table('t_user',
    sa.Column('user_id', sa.INTEGER(), server_default=sa.text("nextval('t_user_user_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('email', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('password_hash', sa.VARCHAR(length=120), autoincrement=False, nullable=False),
    sa.Column('username', sa.VARCHAR(length=120), autoincrement=False, nullable=False),
    sa.Column('created_time', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('user_id', name='t_user_pkey'),
    sa.UniqueConstraint('email', name='t_user_email_key'),
    sa.UniqueConstraint('password_hash', name='t_user_password_hash_key'),
    sa.UniqueConstraint('username', name='t_user_username_key'),
    postgresql_ignore_search_path=False
    )
    op.create_table('t_post',
    sa.Column('post_id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('post_text', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('created_time', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['t_user.user_id'], name='t_post_user_id_fkey'),
    sa.PrimaryKeyConstraint('post_id', name='t_post_pkey')
    )
    op.drop_table('user_model')
    # ### end Alembic commands ###
