"""empty message

Revision ID: 66779c5ba0ba
Revises: 86106d2c94a6
Create Date: 2019-07-26 11:10:57.241273

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '66779c5ba0ba'
down_revision = '86106d2c94a6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('post_point_model', sa.Column('user_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'post_point_model', 'user_model', ['user_id'], ['user_id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'post_point_model', type_='foreignkey')
    op.drop_column('post_point_model', 'user_id')
    # ### end Alembic commands ###
