"""empty message

Revision ID: 819cc3299261
Revises: 66779c5ba0ba
Create Date: 2019-07-26 14:31:32.396557

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '819cc3299261'
down_revision = '66779c5ba0ba'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comment_point_model', sa.Column('user_id', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('comment_point_model', 'user_id')
    # ### end Alembic commands ###
