"""empty message

Revision ID: 86106d2c94a6
Revises: 
Create Date: 2019-07-24 18:02:48.732666

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '86106d2c94a6'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('role_model',
    sa.Column('role_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('role_name', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('role_id'),
    sa.UniqueConstraint('role_name')
    )
    op.create_table('user_model',
    sa.Column('user_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('username', sa.String(length=120), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('password_hash', sa.String(length=120), nullable=False),
    sa.Column('created_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('modified_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('user_id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('password_hash'),
    sa.UniqueConstraint('username')
    )
    op.create_table('post_model',
    sa.Column('post_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('post_text', sa.String(), nullable=False),
    sa.Column('created_time', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user_model.user_id'], ),
    sa.PrimaryKeyConstraint('post_id')
    )
    op.create_table('user_point_model',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('point_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('points', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user_model.user_id'], ),
    sa.PrimaryKeyConstraint('point_id')
    )
    op.create_table('user_roles_model',
    sa.Column('user_role_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('role_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['role_id'], ['role_model.role_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user_model.user_id'], ),
    sa.PrimaryKeyConstraint('user_role_id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_table('comment_model',
    sa.Column('comment_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('post_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('parent_id', sa.Integer(), nullable=True),
    sa.Column('comment_text', sa.String(), nullable=False),
    sa.Column('created_time', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['post_id'], ['post_model.post_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user_model.user_id'], ),
    sa.PrimaryKeyConstraint('comment_id')
    )
    op.create_table('post_point_model',
    sa.Column('post_id', sa.Integer(), nullable=False),
    sa.Column('point_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('points', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['post_id'], ['post_model.post_id'], ),
    sa.PrimaryKeyConstraint('point_id')
    )
    op.create_table('comment_point_model',
    sa.Column('comment_id', sa.Integer(), nullable=False),
    sa.Column('point_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('points', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['comment_id'], ['comment_model.comment_id'], ),
    sa.PrimaryKeyConstraint('point_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('comment_point_model')
    op.drop_table('post_point_model')
    op.drop_table('comment_model')
    op.drop_table('user_roles_model')
    op.drop_table('user_point_model')
    op.drop_table('post_model')
    op.drop_table('user_model')
    op.drop_table('role_model')
    # ### end Alembic commands ###
