"""empty message

Revision ID: 872e92f4501c
Revises: 29abb6625fc2
Create Date: 2019-07-18 17:27:16.055460

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '872e92f4501c'
down_revision = '29abb6625fc2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('t_comment', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('t_comment', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
