"""empty message

Revision ID: b5cd77b55719
Revises: 726c296652ec
Create Date: 2019-07-24 10:49:14.821795

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b5cd77b55719'
down_revision = '726c296652ec'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_point_model',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('point_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('points', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user_model.user_id'], ),
    sa.PrimaryKeyConstraint('point_id')
    )
    op.create_table('post_point_model',
    sa.Column('post_id', sa.Integer(), nullable=False),
    sa.Column('point_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('points', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['post_id'], ['post_model.post_id'], ),
    sa.PrimaryKeyConstraint('point_id')
    )
    op.create_table('comment_point_model',
    sa.Column('comment_id', sa.Integer(), nullable=False),
    sa.Column('point_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('points', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['comment_id'], ['comment_model.comment_id'], ),
    sa.PrimaryKeyConstraint('point_id')
    )
    op.drop_table('point_model')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('point_model',
    sa.Column('entity_type', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('entity_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('point_id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('points', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('point_id', name='point_model_pkey')
    )
    op.drop_table('comment_point_model')
    op.drop_table('post_point_model')
    op.drop_table('user_point_model')
    # ### end Alembic commands ###
