"""empty message

Revision ID: d7e6165b029a
Revises: b5cd77b55719
Create Date: 2019-07-24 15:21:10.311314

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd7e6165b029a'
down_revision = 'b5cd77b55719'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('role_model',
    sa.Column('role_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('role_name', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('role_id'),
    sa.UniqueConstraint('role_name')
    )
    op.create_table('user_roles_model',
    sa.Column('user_role_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('role_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['role_id'], ['role_model.role_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user_model.user_id'], ),
    sa.PrimaryKeyConstraint('user_role_id'),
    sa.UniqueConstraint('user_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_roles_model')
    op.drop_table('role_model')
    # ### end Alembic commands ###
