"""empty message

Revision ID: f0310c8c99d7
Revises: 06be8966a173
Create Date: 2019-07-26 16:50:57.625330

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f0310c8c99d7'
down_revision = '06be8966a173'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('comment_point_model_user_id_fkey', 'comment_point_model', type_='foreignkey')
    op.drop_column('comment_point_model', 'user_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comment_point_model', sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('comment_point_model_user_id_fkey', 'comment_point_model', 'user_model', ['user_id'], ['user_id'])
    # ### end Alembic commands ###
